filebeat.inputs:
- type: log
  enabled: true
  multiline.pattern: '^\{'
  multiline.negate: true
  multiline.match: after
  paths:
    - /var/log/nginx/postdata.log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]